### ISSUE TITLE
Install and Running issue: PyCharm PyDev Connection Refused

### ISSUE THREAD

**Issue by enzyme69** [p4vv37/blender_command_port#12]
I cannot run the addon, it keeps complaining about PyCharm:

```
Traceback (most recent call last):
  File "/Applications/BLENDER_282_OFFICIAL/Blender.app/Contents/Resources/2.82/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/blender_command_port-master/__init__.py", line 18, in <module>
    from .command_port import register as register_command_port
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.82/scripts/addons/blender_command_port-master/command_port.py", line 19, in <module>
    import pydevd_pycharm
ModuleNotFoundError: No module named 'pydevd_pycharm'

```

**Comment by enzyme69** [comment]
After manually installing PyCharm PyDev module, and copy paste into Blender, now it's complaining" Could not connect...

```
Could not connect to localhost: 6666
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.83/python/lib/python3.7/site-packages/_pydevd_bundle/pydevd_comm.py", line 451, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.83/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/blender_command_port-master/__init__.py", line 18, in <module>
    from .command_port import register as register_command_port
  File "/Users/jimmygunawan/Library/Application Support/Blender/2.83/scripts/addons/blender_command_port-master/command_port.py", line 20, in <module>
    pydevd_pycharm.settrace('localhost', port=6666, stdoutToServer=True, stderrToServer=True)
  File "/Applications/Blender.app/Contents/Resources/2.83/python/lib/python3.7/site-packages/pydevd.py", line 1635, in settrace
    stop_at_frame,
  File "/Applications/Blender.app/Contents/Resources/2.83/python/lib/python3.7/site-packages/pydevd.py", line 1682, in _locked_settrace
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/Applications/Blender.app/Contents/Resources/2.83/python/lib/python3.7/site-packages/pydevd.py", line 611, in connect
    s = start_client(host, port)
  File "/Applications/Blender.app/Contents/Resources/2.83/python/lib/python3.7/site-packages/_pydevd_bundle/pydevd_comm.py", line 451, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 61] Connection refused

```

**Comment by enzyme69** [comment]
More info:
I am using MacOS Catalina 15.15.5 and Blender 2.83 beta.

**Comment by davidAlgis** [comment]
I have the same issue on windows 10 and blender 9.2

**Comment by davidAlgis** [comment]
I solve this issue by removing the lines 19 and 20:
```
import pydevd_pycharm
pydevd_pycharm.settrace('localhost', port=6666, stdoutToServer=True, stderrToServer=True)
```
 of  ``command_port.py`` file.
